Release v0.6.0
prometheus/collectd_exporter pull request #147
Opened 2023-12-08 22:51 UTC by blkperl

* [CHANGE] Update minimum Go version to 1.20 (#145)
* [FEATURE] Add TLS authentication using official exporter-toolkit (#113)
* [BUGFIX] Restore version command line flag and fix build info (#104)
* [FEATURE] Added s390x support to docker image (#98)

2023-12-08 22:54 UTC, blkperl commented on CHANGELOG.md
> +## 0.6.0 / 2023-12-08
@SuperQ reminder to change this date before merge :)

2023-12-09 09:33 UTC, SuperQ requested changes

2023-12-09 09:33 UTC, SuperQ commented on CHANGELOG.md
> +* [CHANGE] Update minimum Go version to 1.20 (#145)
We don't typically mention non-user-facing changes like build stuff.

```suggestion
```

2023-12-09 09:33 UTC, SuperQ commented on CHANGELOG.md
> +## 0.6.0 / 2023-12-08
```suggestion
## 0.6.0 / 2023-12-09
```

2023-12-09 09:33 UTC, SuperQ commented on CHANGELOG.md
> +* [FEATURE] Added s390x support to docker image (#98)
Usually we group things by category in the order of CHANGE, FEATURE, ENHANCEMENT, BUGFIX.

2023-12-09 17:40 UTC, blkperl commented on CHANGELOG.md
> +* [FEATURE] Added s390x support to docker image (#98)
Fixed!

2023-12-09 20:51 UTC, SuperQ approved these changes

2023-12-09 20:51 UTC, merged